image:
  file: .gitpod/Dockerfile

tasks:
  - name: Restore and build
    init: |
      dotnet dev-certs https 
      dotnet tool restore
  - name: Run
    command: dotnet run

vscode:
  extensions:
    - Ionide.Ionide-fsharp
    - muhammad-sammy.csharp